Fix `_base_cmaskcar` destructor (#17)
* Fix `_base_cmaskcar` destructor

Given the following minimal script:

    from vsmasktools import CustomMaskFromRanges
    from vstools import core, set_output

    mask = CustomMaskFromRanges(ranges={})
    set_output(core.std.BlankClip())

Opening this in vs-preview and then closing the program yields the
following error:

    Traceback (most recent call last):
      File "vstools/utils/vs_proxy.py", line 351, in _finalize_core
        callback(env_id, core_id)
    TypeError: _base_cmaskcar.__vs_del__() takes 2 positional arguments but 4 were given

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "Lib/weakref.py", line 666, in _exitfunc
        f()
      File "Lib/weakref.py", line 590, in __call__
        return info.func(*info.args, **(info.kwargs or {}))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "vstools/utils/vs_proxy.py", line 384, in <lambda>
        weakref.finalize(_vs_core, lambda: _finalize_core(env_id, core_id, False))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "vstools/utils/vs_proxy.py", line 353, in _finalize_core
        callback()
      File "vsmasktools/hardsub.py", line 50, in __vs_del__
        super().__vs_del__(core_id)
        ^^^^^^^^^^^^^^^^^^
    AttributeError: 'super' object has no attribute '__vs_del__'

AFAICT there isn't actually a `super().__vs_del__()` to call (this only
inherits from `vs_object`), and none of the other examples of
`__vs_del__()` throughout JET have this pattern, so this patch removes
it.

* Stop skipping mypy in CI

But ignore existing errors for now.